/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eu.bambooapps.gradle.plugin.githook

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.Exec
import org.gradle.kotlin.dsl.create
import org.gradle.kotlin.dsl.provideDelegate
import org.gradle.kotlin.dsl.register
import org.gradle.kotlin.dsl.registering

/**
 * Plugin that helps to copy git hooks to the .git folder from the specified directory
 */
class GitHookPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create<GitHooksExtension>("gitHooks")
        // Register a task
        project.tasks.register<CopyGitHooks>("copyGitHooks") {
            description = "Copies the git hooks from /git-hooks to the .git folder."
            group = "git hooks"
            gitHooksDirectory.set(extension.gitHooksDirectory)
            gitHooksDestinationDirectory.set(
                project.rootProject.layout.projectDirectory.dir(".git/hooks")
            )
            onlyIf { isLinuxOrMacOs() }
        }


        project.tasks.register<InstallGitHooks>("installGitHooks") {
            description = "Installs the pre-commit git hooks from /git-hooks."
            group = "git hooks"
            dependsOn("copyGitHooks")
            onlyIf { isLinuxOrMacOs() }
            doLast {
                logger.debug("Git hook installed successfully.")
            }
        }
    }

    private fun isLinuxOrMacOs(): Boolean {
        val osName = System.getProperty("os.name").lowercase()
        return osName.contains("linux") ||
                osName.contains("mac os") ||
                osName.contains("macos")
    }
}
