/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eu.bambooapps.gradle.plugin.githook

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'eu.bambooapps.gradle.plugin.githook.greeting' plugin.
 */
class GitHookPluginPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("eu.bambooapps.gradle.plugin.githook.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
